/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LabRouteImport } from './routes/lab'
import { Route as WorkIdRouteImport } from './routes/work.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdRoute = WorkIdRouteImport.update({
  id: '/work/$id',
  path: '/work/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lab': typeof LabRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lab': typeof LabRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lab': typeof LabRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/lab' | '/work/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/lab' | '/work/$id'
  id: '__root__' | '/' | '/about' | '/lab' | '/work/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LabRoute: typeof LabRoute
  WorkIdRoute: typeof WorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/work/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LabRoute: LabRoute,
  WorkIdRoute: WorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
